export enum ActionType {
    ADD_TOPIC = 'addTopic',
    REMOVE_TOPIC = 'removeTopic',
    RESET_CRYPTO_DATA = 'resetCryptoData',
    SET_CRYPTO_DATA = 'setCryptoData',
    SET_CRYPTO_DATA_ERROR = 'setCryptoDataError',
    SET_CRYPTO_FREQUENCY = 'setCryptoFrequency',
    SET_CURRENT_TOPIC = 'setCurrentTopic',
    SET_CURRENT_WEATHER = 'setCurrentWeather',
    SET_CURRENT_WEATHER_ERROR = 'setCurrentWeatherError',
    SET_DOODLES = 'setDoodles',
    SET_DOODLES_ERROR = 'setDoodlesError',
    SET_RSS_DATA = 'setRssData',
    SET_RSS_ERROR = 'setRssError',
    SET_TOPICS = 'setTopics',
}
